apiVersion: apps/v1
kind: Deployment
metadata:
  name: meilisearch-paopao
  namespace: paopao-app
  labels:
    app.kubernetes.io/name: meilisearch-paopao
    app.kubernetes.io/instance: meilisearch-paopao
    app.kubernetes.io/version: "1.2.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: meilisearch-paopao
      app.kubernetes.io/instance: meilisearch-paopao
  template:
    metadata:
      labels:
        app.kubernetes.io/name: meilisearch-paopao
        app.kubernetes.io/instance: meilisearch-paopao
    spec:
      serviceAccountName: meilisearch-paopao
      securityContext:
        {}
      containers:
        - name:  meilisearch-paopao
          securityContext:
            {}
          image: getmeili/meilisearch:v1.4
          imagePullPolicy: IfNotPresent
          env:
          - name: MEILI_MASTER_KEY
            value: paopao-meilisearch
          ports:
            - containerPort: 7700
              name: meilisearch
              protocol: TCP