apiVersion: v1
kind: ServiceAccount
metadata:
  name: meilisearch-paopao
  namespace: paopao-app
  labels:
    app.kubernetes.io/name: meilisearch-paopao
    app.kubernetes.io/instance: meilisearch-paopao
    app.kubernetes.io/version: "1.22.0"