apiVersion: v1
kind: Service
metadata:
  name: meilisearch-paopao
  namespace: paopao-app
  labels:
    app.kubernetes.io/name: meilisearch-paopao
    app.kubernetes.io/instance: meilisearch-paopao
    app.kubernetes.io/version: "1.2.0"
spec:
  type: ClusterIP
  ports:
    - port: 7700
      targetPort: meilisearch
      protocol: TCP
      name: meilisearch
  selector:
    app.kubernetes.io/name: meilisearch-paopao
    app.kubernetes.io/instance: meilisearch-paopao