apiVersion: v1
kind: ServiceAccount
metadata:
  name: paopao-backend
  namespace: paopao-app
  labels:
    app.kubernetes.io/name: paopao-backend
    app.kubernetes.io/instance: paopao-backend
    app.kubernetes.io/version: "1.22.0"