apiVersion: v1
kind: ServiceAccount
metadata:
  name: redis-paopao
  namespace: paopao-app
  labels:
    app.kubernetes.io/name: redis-paopao
    app.kubernetes.io/instance: redis-paopao
    app.kubernetes.io/version: "1.22.0"