apiVersion: v1
kind: Service
metadata:
  name: redis-paopao
  namespace: paopao-app
  labels:
    app.kubernetes.io/name: redis-paopao
    app.kubernetes.io/instance: redis-paopao
    app.kubernetes.io/version: "1.2.0"
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    app.kubernetes.io/name: redis-paopao
    app.kubernetes.io/instance: redis-paopao