apiVersion: v1
kind: ServiceAccount
metadata:
  name: mysql-paopao
  namespace: paopao-app
  labels:
    app.kubernetes.io/name: mysql-paopao
    app.kubernetes.io/instance: mysql-paopao
    app.kubernetes.io/version: "1.22.0"