apiVersion: v1
kind: ServiceAccount
metadata:
  name: paopao-web
  namespace: paopao-app
  labels:
    app.kubernetes.io/name: paopao-web
    app.kubernetes.io/instance: paopao-web
    app.kubernetes.io/version: "1.22.0"